build.gradle, src/main/java/com/kakaotech/team14backend/config/RedisConfig.java, src/main/java/com/kakaotech/team14backend/inner/image/model/Image.java, src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java, src/main/java/com/kakaotech/team14backend/inner/member/usecase/FindMemberUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/model/Post.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/CreatePostUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPostUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/CreatePostDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPostDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPostResponseDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/UploadPostDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java, src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java, src/main/resources/application.properties, src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPostUsecaseTest.java
이 PR에서는 조회수 중복 증가 방지 및 Redis 관련 설정 코드를 작성했습니다.
- RedisTemplate의 Set 자료구조를 이용해 조회수 중복 증가 방지 기능 구현 
- 각 계층별(Controller, Service, Usecase, Mapper, Repository) 게시글 상세 조회 기능 구현
- 기존의 DTO 방식에서 Record 클래스를 DTO로 사용하는 방식으로 리팩토링 및 기능 구현
- RedisConfig 등과 같은 Redis 관련 설정
- FindPostUsecaseTest를 통해 조회수 중복 기능 검증
- 이슈번호: #19 
아직 해당 이슈관련 구현이 끝나지 않았으나, Redis관련 설정 공유를 위해 PR 함.
=> feat : 조회수 중북 증가 방지 및 Redis 관련 설정

src/main/java/com/kakaotech/team14backend/inner/post/repository/PostRepository.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPostListUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPostListResponseDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java, src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java, src/main/resources/db/teardown.sql, src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPostListUsecaseTest.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
홈 피드의 무한 스크롤 기능을 구현하고 테스트 데이터를 업데이트하기 위한 여러 커밋을 포함하고 있습니다.
- PostController의 올바른 기능을 보증하기 위해 테스트 케이스를 추가했습니다.
- 사용자가 게시물을 보기 위해 홈 피드 검색 기능이 구현되었습니다.
- 홈 피드 조회를 위한 Usecase를 추가하였습니다.
- 무한 스크롤 기능을 구현하여 사용자가 홈 피드에서 더 많은 게시물을 볼 수 있습니다.
- `hasNext` 플래그를 도입하여 무한 스크롤 기능을 최적화하고 클라이언트에게 더 많은 데이터의 존재를 알릴 수 있도록 수정하였습니다.
- 테스트를 위한 초기 데이터를 생성하는 SQL 스크립트를 추가하였습니다.
=> 무한 스크롤 기능 구현 및 테스트 데이터 업데이트

build.gradle, src/main/java/com/kakaotech/team14backend/config/SwaggerConfig.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/main/resources/application.properties
- `SwaggerConfig.java` 설정 파일을 추가하여 Swagger 3.0 API 문서화를 활성화했습니다.
- 설정에서는 `@RestController` 애노테이션이 있는 컨트롤러만 문서화 대상으로 포함시켰습니다.
- 애플리케이션 프로퍼티에서 매칭 전략을 설정하여 swagger 3.0 경로 에러를 해결했습니다.
- API 문서화를 개선하고, swagger 3.0 경로 에러를 해결하기 위함입니다.
1. Swagger UI를 통해 모든 `@RestController` 애노테이션이 있는 컨트롤러가 문서화되었는지 확인합니다.
2. 경로 에러가 해결되어 API 문서가 올바르게 표시되는지 확인합니다.
- 이슈 #27
=> feat: Swagger 3.0 설정 추가

build.gradle, src/main/java/com/kakaotech/team14backend/Team14BackendApplication.java, src/main/java/com/kakaotech/team14backend/config/CacheProperties.java, src/main/java/com/kakaotech/team14backend/config/RedisConfig.java, src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java, src/main/java/com/kakaotech/team14backend/inner/post/model/Post.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPostUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostViewCountUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostViewCountUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java, src/main/resources/application.properties, src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPostUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostViewCountUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostViewCountUsecaseTest.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
게시글 상세 조회 및 조회수 그리고 인기 게시글 조회 기능 구현을 하였습니다.
- 캐시 전략으로 인해 홈 피드 게시글 상세 조회와 인기 게시글 상세 조회를 분리하였습니다.
- 인기 게시글 상세 조회할 때는 캐시 전략으로 Look Aside 패턴을 사용하였습니다.
- 게시글의 조회가 빈번하고, 캐시 서버에 문제가 생겨 조회수 값이 DB에 반영이 되지 않다러도 정책에 따라서 큰 문제가 없다고 판단하여 캐시 전략으로 Wriete Back 패턴을 사용하였습니다.
todo : 캐시 서버에 문제가 생겼을 때 DB에 조회수 값이 누락되지 않고 잘 반영되게 만드는 방법 생각
- 한 게시글에 사용자가 10분 이내에 여러번 방문해도 조회수는 1로 유지됩니다.
=> 인기게시글 상세 조회 및 조회수 관련 기능 구현 및 레디스 관련 설정

src/main/resources/db/teardown.sql, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
member 테이블과 post 테이블의 변경 사항을 반영하여 SQL teardown 스크립트를 수정했습니다.
SQL 스크립트 내의 member 테이블에 role 컬럼을 추가했습니다.
이슈: #18
=> fix: 멤버와 포스트 변경으로 인한 Home Feed controller Test 에러 해결

src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java, src/main/java/com/kakaotech/team14backend/inner/post/model/Post.java, src/main/java/com/kakaotech/team14backend/inner/post/model/PostLike.java, src/main/java/com/kakaotech/team14backend/inner/post/model/PostLikeHistory.java, src/main/java/com/kakaotech/team14backend/inner/post/repository/PostLikeHistoryRepository.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/CreatePostLikeHistoryUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPostLikeHistoryDTO.java
새로운 엔티티인 `PostLikeHistory`를 추가하여 사용자의 좋아요 이력을 관리하게 되었습니다. 
이 엔티티는 `Member`와 `Post` 엔티티와 다대일 관계를 형성하여 어떤 사용자가 어떤 게시물에 좋아요를 눌렀는지의 이력을 저장하게 됩니다. 
이는 추후 좋아요 취소 시 이력을 삭제하기 위한 목적으로 사용됩니다.
`CreatePostLikeHistoryUsecase` 클래스를 통해 좋아요가 추가되고, Redis 스케줄링을 통해 DB에 저장되는 순간에 `PostLikeHistory`를 생성하도록 구현하였습니다. 
이 유즈케이스는 `getPostLikeHistoryDTO`를 인자로 받아서, 해당 데이터를 기반으로 `PostLikeHistory` 엔티티를 생성하고 저장하게 됩니다.
또한, 좋아요 취소 시 `PostLikeHistory`를 삭제하는 기능은 추후 구현 예정입니다.
=> feat: PostLikeHistory 엔티티 및 좋아요 이력 관리 유즈케이스 구현

src/main/java/com/kakaotech/team14backend/inner/post/model/Post.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostPopularityUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostViewCountUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostPopularityUsecase.java, src/main/resources/application.properties, src/test/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostPopularityUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostViewCountUsecaseTest.java
스케줄링과 트랜잭션을 담당하는 클래스를 분리하고, 인기도 업데이트 스케줄링 테스트하는 코드를 작성하였습니다.
=>  인기도 업데이트 스케줄링 테스트

src/main/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostLikeCountUsecase.java, src/main/resources/db/teardown.sql, src/test/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostLikeCountUsecaseTest.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
- 기존의 레디스 캐시에서 좋아요 수를 가져오는 부분, 주석 처리되어 있고, 대신 데이터베이스에서 직접 좋아요 수를 가져와 업데이트합니다.
- teardown.SQL 파일의 member 상태 enum이 반영
- 테스트에서 teardown.SQL 터지던 문제가 해결 (likeCount 테이블 초기화를 하지 않아서 발생한 문제)
SQL 스크립트는 데이터를 리셋하고 테이블 간의 관계를 유지하기 위해 참조 무결성을 일시적으로 비활성화/활성화합니다. 
이러한 방식으로 테이블의 데이터를 초기 상태로 리셋하고, 이전에 발생했던 유일성 또는 기본 키 제약 조건 위반 문제를 해결하였습니다
=> likeCount 최소 기능 구현 완료

src/main/java/com/kakaotech/team14backend/exception/Exception400.java, src/main/java/com/kakaotech/team14backend/exception/Exception401.java, src/main/java/com/kakaotech/team14backend/exception/Exception403.java, src/main/java/com/kakaotech/team14backend/exception/Exception404.java, src/main/java/com/kakaotech/team14backend/exception/Exception500.java, src/main/java/com/kakaotech/team14backend/exception/GlobalExceptionHandler.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
- 전역 예외 핸들러 GlobalExceptionHandler 클래스를 구현하여 프로젝트 전반에 걸쳐 일관된 예외 처리를 제공합니다.
- 각 HTTP 상태 코드(400, 401, 403, 404, 500)에 대한 예외 클래스를 정의하고, GlobalExceptionHandler에서 이를 처리합니다.
- 게시물 조회 API의 getPosts 메소드에서 size와 lastPostId 파라미터의 유효성을 검사하고, 유효하지 않은 값이 전달될 경우 Exception400 예외를 발생시킵니다.
- 해당 예외는 GlobalExceptionHandler에서 처리되어 클라이언트에게 적절한 에러 응답을 반환합니다.
- 기본적인 예외를 만들고, 세부 사항들은 점차 추가 할 예정입니다
- [Sonny](@hwangdaesun)님 코드보니 Message Code에서 예외 코드를 Enum으로 정하고 있어 Sonny 랑 예외 관련 이야기하면 좋을거 같아요! 
이슈 번호 :  #61
=> 전역 예외 핸들러 구현 및 게시물 조회 API 예외 처리 개선

src/main/java/com/kakaotech/team14backend/common/RedisKey.java, src/main/java/com/kakaotech/team14backend/common/ScanRedisKey.java, src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPopularPostListUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPostViewCountUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostViewCountUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java, src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java, src/main/resources/db/teardown.sql, src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPopularPostListUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPostViewCountUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostViewCountTest.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
인기 피드 상세 조회 및 전체조회 관련 코드들을 리팩토링하였습니다.
todo : 기능 개발이 완성된 후 캐시 도입
=> 인기 피드 리팩토링 및 테스트 보충

src/main/java/com/kakaotech/team14backend/inner/post/repository/PostRepository.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPersonalPostListUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPersonalPostListResponseDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPersonalPostResponseDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java, src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
"My Page" 기능에 유저가 올린 게시물을 조회하는 기능을 구현한 내용을 포함하고 있습니다. 
이 작업은 Pair Programming을 통해 수행되었으며, 다음과 같은 주요 변경사항을 포함하고 있습니다:
@GetMapping("/post/user") 엔드포인트를 추가하여 유저가 올린 게시물을 조회할 수 있도록 함
사용자 ID, 마지막 게시물 ID, 페이지 크기를 파라미터로 받아 조회 기능을 구현.
GetPersonalPostListResponseDTO를 사용하여 응답을 생성.
1. 게시물 조회 기능 추가
2. API 엔드포인트 추가
3. DTO 클래스 추가
4. 서비스 및 유즈케이스 로직 추가
=> My Page 유저가 올린 게시물들 조회하는 기능 구현 with PairProgramming

src/main/java/com/kakaotech/team14backend/inner/point/usecase/CreatePointUsecase.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPopularPostListUsecaseTest.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
각 테스트의 독립성을 보장하기 위해 테스트에 맞게 Redis 관련 데이터를 삭제하거나 세팅하였습니다.
관련 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/87
=> 인기 피드 전체 조회 기능 - 단위테스트는 성공하지만, "Run all Tests"로 모든 단위테스트를 한번에 돌릴 때는 실패하는 이슈 해결

src/main/java/com/kakaotech/team14backend/common/FileUtils.java, src/main/java/com/kakaotech/team14backend/common/MessageCode.java, src/main/java/com/kakaotech/team14backend/exception/GlobalExceptionHandler.java, src/main/java/com/kakaotech/team14backend/exception/MaxLevelSizeException.java, src/main/java/com/kakaotech/team14backend/exception/MemberNotFoundException.java, src/main/java/com/kakaotech/team14backend/exception/MultiplePostsFoundException.java, src/main/java/com/kakaotech/team14backend/exception/PostNotFoundException.java, src/main/java/com/kakaotech/team14backend/inner/member/usecase/FindMemberUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java
기존의 예외를 Http Status별로 정의하는 방식에서 예외를 따로따로 나누는 방식으로 변경하였습니다.
1.  exception 패키지에서 예외를 정의
2. 해당 예외에 맞는 MessageCode 생성
3. 각 layer에서 예외 발생
4. GlobalExceptionHandle에서 예외 핸들링 메서드 생성
관련 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/123
todo : 각자 맞은 기능을 위의 예외 처리 방식으로 변경해주세요!
=> 예외 처리 전략 변경

src/main/java/com/kakaotech/team14backend/common/FileUtils.java, src/main/java/com/kakaotech/team14backend/inner/image/model/Image.java
1. 이미지 경로가 없는 경우 예외 처리가 안되어 있음
2. 이미지 도메인의 엔티티가 20자로 제한이 되어 있어, 이미지 이름이 길면 받지 않는 이슈가 있음
이슈 번호 : #130
=> refactor : 이미지 경로 없을 시 생성하도록 수정

src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPostListUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPostListResponseDTO.java, src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java
- 클라이언트로부터 요청받은 페이지네이션 크기를 처리하기 위해 동적 size 파라미터를 추가하였습니다.
- 원본 포스트 리스트를 셔플하지 않고 랜덤 포스트 선택을 구현하기 위해 새로운 메서드를 사용하였습니다.
- 현재 페이지네이션된 리스트를 기반으로 다음 페이지에 대한 lastPostId를 가져오는 로직을 업데이트하였습니다.
- 페이지네이트할 더 이상의 포스트가 없을 때 lastPostId를 null로 설정하도록 했습니다.
- 포스트 리스트 크기가 요청된 크기보다 작은 경우를 처리하기 위해 로직을 조정하였습니다.
- lastPostId, 랜덤으로 선택된 포스트, 그리고 hasNext 플래그를 포함하여 반환문을 업데이트하였습니다.
=> FindPostListUsecase에서 랜덤 포스트 선택과 페이지네이션 구현

k8s/configs/default.conf, src/main/java/com/kakaotech/team14backend/outer/member/controller/MemberController.java, src/main/java/com/kakaotech/team14backend/outer/member/dto/GetMemberInfoResponseDTO.java, src/main/java/com/kakaotech/team14backend/outer/member/service/MemberService.java, src/main/resources/db/prodMockSetup.sql
```java
@RequestMapping("/api")
public class MemberController {
private final MemberService memberService;
```
```java
@ApiOperation(value = "마이페이지 계정 상세 조회")
@GetMapping("/user/info")
public ApiResponse<ApiResponse.CustomBody<GetMemberInfoResponseDTO>> getMyPageInfo(
@AuthenticationPrincipal PrincipalDetails principalDetails) {
```
```java
-- Image Table
INSERT INTO image (created_at, image_uri)
VALUES (NOW(), '/images/test.jpg'),
(NOW(), '/images/test.jpg'),
(NOW(), '/images/test.jpg'),
(NOW(), '/images/test.jpg'),
(NOW(), '/images/test.jpg'),
(NOW(), '/images/test.jpg'
```
=> Fix : User Info User Null 이슈 해결 및 Mock Up setting 변경

src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java
- PostController의 getPost 메서드에 @AuthenticatoinPrincipal 적용
- PostController의 getPopularPost 메서드에 @AuthenticatoinPrincipal 적용
- PostController의 uploadPost 메서드에 @AuthenticatoinPrincipal 적용
관련 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/157
=> 게시물 업로드 및 조회시 실제 사용자가 수행 하고 있는 것으로 수정

src/main/java/com/kakaotech/team14backend/filter/FilterResponseUtils.java, src/main/resources/application-prod.yml
* 엑세스토큰 만료 상태코드 -> 4111 로 설정
* redirect uri -> https://localhost:443/instagram/callback 으로 설정
=> 엑세스토큰 만료 상태코드 및 https redirect-uri 설정

src/main/java/com/kakaotech/team14backend/filter/FilterResponseUtils.java, src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java, src/main/java/com/kakaotech/team14backend/inner/member/model/Status.java, src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java, src/main/java/com/kakaotech/team14backend/outer/member/service/MemberService.java
* 회원탈퇴 시 사용자 상태 "INACTIVE"로 변경
* 토큰 재발급이 필요한 상태 시 '4111' 코드 반환
TODO : INACTIVE 상태 한달 유지 시 데이터 삭제 로직 처리
=> 회원탈퇴 기능 수정 및 엑세스토큰 만료 상태코드 변경

src/main/java/com/kakaotech/team14backend/common/MessageCode.java, src/main/java/com/kakaotech/team14backend/inner/post/model/PostRandomFetcher.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUsecase.java, src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPostListUsecase.java, src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java, src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java, src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java, src/test/java/com/kakaotech/team14backend/inner/post/model/PostRandomFetcherTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUnder30Test.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUsecaseOver30Test.java, src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
주요 변경 사항
---
1. DB에 저장되어있는 게시글의 개수가 인기 피드 전체 조회 시 요구하는 게시글 size의 총합보다 작을 경우를 고려
2. DB에 저장되어있는 게시글의 갯수가 랭킹 최하위 순위보다 적을 경우를 고려
3. 조회시 모든 게시글의 레벨이 없을 경우 고려
위 3가지를 고려하여 인기 피드 리팩토링 및 테스트 수행
관련 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/159
=> 인기 피드 조회시 DB에 저장되어 있는 게시글의 갯수가 랭킹 최하위 순위의 개수보다 적을 경우 고려

src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java, src/main/java/com/kakaotech/team14backend/outer/member/service/MemberService.java, src/main/resources/db/prodMockSetup.sql, src/main/resources/db/testSetup.sql, src/test/java/com/kakaotech/team14backend/inner/member/repository/MemberRepositoryTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/SetPostLikeUsecaseTest.java, src/test/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostViewCountTest.java
기존 auto_increment로 생성되는 memberId PK를 카카오에서 제공해주는 UUID인 kakaoId와 동일하 값으로 설정
=> fix : member 엔티티 pk 수정

src/main/java/com/kakaotech/team14backend/outer/login/service/InstagramService.java
* 이전 인스타연동 시 기존 리프레시토큰을 삭제해주는 로직이 사실 필요없는 과정이라서 다시 생략하였습니다.
=> fix : 인트사연동 수정사항 롤백
