.editorconfig
.gitignore

빌드 결과물, IDE 파일, OS 특정 파일과 같은 불필요한 파일들이 저장소에 커밋되는 것을 방지하기 위해 추가하였습니다. 
저장소를 깔끔하고 집중된 상태로 유지할 수 있습니다.
다양한 편집기와 IDE에서 사용하는 팀원 간에 일관된 코딩 스타일을 적용하기 위해 추가하였습니다. 
이를 통해 코드가 읽기 쉽고 유지보수하기 쉬워집니다.
이슈 #1 해결

프로젝트 개발환경 설정

---

build.gradle
src/main/java/com/kakaotech/team14backend/common/ApiResponse.java
src/main/java/com/kakaotech/team14backend/common/ApiResponseGenerator.java
src/main/java/com/kakaotech/team14backend/common/Error.java
src/main/java/com/kakaotech/team14backend/common/FileUtils.java
src/main/java/com/kakaotech/team14backend/common/MessageCode.java
src/main/java/com/kakaotech/team14backend/common/UploadFileDTO.java
src/main/java/com/kakaotech/team14backend/config/AutoAppConfig.java
src/main/java/com/kakaotech/team14backend/config/WebConfig.java
src/main/java/com/kakaotech/team14backend/exception/ExtentionNotAllowedException.java
src/main/java/com/kakaotech/team14backend/inner/image/model/Image.java
src/main/java/com/kakaotech/team14backend/inner/image/repository/ImageRepository.java
src/main/java/com/kakaotech/team14backend/inner/image/usecase/CreateImageUsecase.java
src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
src/main/java/com/kakaotech/team14backend/inner/member/repository/MemberRepository.java
src/main/java/com/kakaotech/team14backend/inner/member/usecase/FindMemberUsecase.java
src/main/java/com/kakaotech/team14backend/inner/post/model/Post.java
src/main/java/com/kakaotech/team14backend/inner/post/repository/PostRepository.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/CreatePostUsecase.java
src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java
src/main/java/com/kakaotech/team14backend/outer/post/dto/UploadPostRequestDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java
src/main/resources/application.properties

이 PR에서는 게시글 업로드, 파일 관리 기능을 구현하였습니다. 다양한 엔터티, DTO, 서비스 로직, 컨트롤러 등이 추가되었습니다.
- `Post`, `Image`, `Member` 엔터티 및 레포지터리를 구현하고 관계 설정
- API 응답과 예외 처리를 위한 `ApiResponse`, `Error` 클래스 추가
- 파일 관리를 위한 `FileUtils`, `UploadFileDTO` 구현
- 클린 아키텍처를 고려한 `usecase`와 `service` 로직 구현
- 게시글 업로드를 위한 `PostController`와 `UploadPostRequestDTO` 구현
- 이슈번호: #7

feat: 게시글 및 파일 관리 기능 구현

---

README.md

해당 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/31

docs : readMe 작성

---

src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
src/main/java/com/kakaotech/team14backend/outer/login/service/PrincipalOauth2UserService.java

refactor : 로그인 및 회원가입 관련 코드 리팩토링

---

src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java
src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java

Post Controller와 테스트 코드의 잘못된 상태 코드 수정 및 Code Style 적용했습니다!

fix : Post status typo

---

src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/filter/FilterResponseUtils.java

기존 인증실패 및 권한미달로 인한 코드 가독성있게 리팩토링하였습니다!

SecurityConfig 클래스 리팩토링

---

src/main/java/com/kakaotech/team14backend/inner/post/repository/PostLikeRepository.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/SetPostLikeUsecase.java

- `SetPostLikeUsecase` 리팩토링: Redis 제거, DB 사용
- 회원, 게시글 유효성 검증 추가
- 이슈 번호: #39
이제 Redis 붙이는 방향으로 고도화 하겠습니다

feat : 좋아요 로직 리팩토링 및 Redis 제거

---

src/main/java/com/kakaotech/team14backend/auth/AuthenticationSuccessHandler.java
src/main/java/com/kakaotech/team14backend/common/MessageCode.java
src/main/java/com/kakaotech/team14backend/exception/MemberNotFoundException.java
src/main/java/com/kakaotech/team14backend/exception/TokenValidationException.java
src/main/java/com/kakaotech/team14backend/jwt/Controller/JwtController.java
src/main/java/com/kakaotech/team14backend/jwt/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/team14backend/jwt/repository/RefreshTokenRepository.java
src/main/java/com/kakaotech/team14backend/jwt/service/TokenService.java

* 기존 TokenService의 안티코드 요소를 제거하기 위해서 코드를 수정해보았습니다. 
* 수정할 사항이 여전히 보인다면 피드백 주시며 감사하겠습니다.
* reassigned 항목 수정
* 예외처리 항목 자세하게 수정
* 그 밖의 Exception 클래스 추가
몇분전 올라온 범수님 PR에서 전역예외핸들러가 구현되었던데, 해당 사항 적용하게 추후 수정하도록 하겠습니다!!

로그인 관련 코드 리팩토링

---

src/main/java/com/kakaotech/team14backend/Mypage/MyPageServlet.java
src/main/java/com/kakaotech/team14backend/Mypage/PostDAO.java
src/main/java/com/kakaotech/team14backend/Mypage/mypage.jsp

DAO 클래스에 게시물 조회 메서드 추가
서블릿에서 게시물 조회 요청 처리
JSP 파일 작성

마이페이지 게시물 조회

---

src/main/java/com/kakaotech/team14backend/auth/AuthenticationSuccessHandler.java
src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
src/main/java/com/kakaotech/team14backend/inner/member/service/MemberService.java
src/main/java/com/kakaotech/team14backend/jwt/service/TokenService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/PrincipalOauth2UserService.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPopularPostListUsecaseTest.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostPopularityTest.java

* UserService 클래스작성 및 CreateMember 메소드 작성
* 기존 Member.createMember() -> memberService.createMember() 실행하도록 변경

UserService 클래스 작성

---

src/main/java/com/kakaotech/team14backend/jwt/Controller/JwtController.java
src/main/java/com/kakaotech/team14backend/outer/login/controller/LoginController.java

style : Controller 클래스 수정

---

build.gradle
src/main/java/com/kakaotech/team14backend/common/RedisKey.java
src/main/java/com/kakaotech/team14backend/inner/post/model/PostRandomFetcher.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUsecase.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostUsecase.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPopularPostListUsecase.java
src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java
src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java
src/main/resources/application.yml
src/test/java/com/kakaotech/team14backend/inner/post/repository/PostRepositoryTest.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostListUsecaseTest.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPopularPostListUsecaseTest.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/SaveTemporaryPostViewCountUsecaseTest.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostPopularityTest.java
src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java

인기 피드 상세 조회 및 전체조회 관련 코드들을 리팩토링하였습니다.

인기 피드 리팩토링 및 테스트 보충

---

src/main/java/com/kakaotech/team14backend/inner/point/model/Point.java
src/main/java/com/kakaotech/team14backend/inner/point/model/PointHistory.java
src/main/java/com/kakaotech/team14backend/inner/point/model/PointPolicy.java
src/main/java/com/kakaotech/team14backend/inner/point/model/TransactionType.java
src/main/java/com/kakaotech/team14backend/inner/point/repository/PointHistroyRepository.java
src/main/java/com/kakaotech/team14backend/inner/point/repository/PointRepository.java
src/main/java/com/kakaotech/team14backend/inner/point/usecase/CreatePointUsecase.java
src/main/java/com/kakaotech/team14backend/inner/point/usecase/GetPointUsecase.java
src/main/java/com/kakaotech/team14backend/inner/point/usecase/UsePointUsecase.java
src/main/java/com/kakaotech/team14backend/outer/member/service/MemberService.java

포인트 기능을 구현하는 데 필요한 엔티티와 usecase 생성
관련 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/88

포인트 관련 SetUp

---

src/main/java/com/kakaotech/team14backend/inner/post/model/PostLike.java
src/main/java/com/kakaotech/team14backend/inner/post/repository/PostLikeRepository.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/SetPostLikeUsecase.java
src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/SetPostLikeUsecaseTest.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostLikeCountUsecaseTest.java

좋아요 로직을 최적화하고, 모킹(Mocking) 데이터를 사용하여 테스트를 수행하도록 변경하였으며, 로직 역시 수정되어 좋아요 상태를 계속 추가하고 최근 상태를 가져오도록 변경되었습니다.
이제 좋아요 상태를 계속 추가하고 최근 상태를 가져오는 방식으로 변경되었습니다.
이로 인해 기존의 삭제 및 재생성 대신에 상태 변경이 이루어집니다.
인덱스를 사용하여 Full Scan 이슈를 방지합니다.
모킹(Mocking) 데이터를 사용하여 테스트를 수행하도록 수정되었습니다.

좋아요 로직 최적화 

---

src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
src/main/java/com/kakaotech/team14backend/outer/login/dto/InstagramAccessTokenDto.java
src/main/java/com/kakaotech/team14backend/outer/login/service/InstagramService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/TokenMemoryStorageService.java
src/main/resources/application-local.yml

* 인스타그램 Oauth2서버를 통한 사용자 계정 정보 조회
* 카카오 및 인스타그램 인증코드 발급 프론트엔드로 인가
* 외부API 요청 시 프록시 서버 설정

인스타그램 연동 기능 개발

---

src/main/java/com/kakaotech/team14backend/inner/post/model/PostRandomFetcher.java
src/test/java/com/kakaotech/team14backend/inner/post/study/RandomTest.java

Random 클래스를 ThreadLocalRandom 클래스로 변경
이슈 번호 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/106

PostRandomFetcher에서 Random 클래스를 ThreadLocalRandom 클래스로 변경

---

src/main/java/com/kakaotech/team14backend/inner/post/model/Post.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/UpdatePostPopularityUsecase.java
src/test/java/com/kakaotech/team14backend/inner/post/model/PostTest.java

테스트 불가능한 로직에서 테스트 가능한 로직으로 리팩토링하고 유닛 테스트 추가
이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/111

Post 엔티티와 UpdatePostPopularityUsecase 유스케이스 리팩토링

---

src/main/java/com/kakaotech/team14backend/jwt/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/team14backend/outer/login/controller/LoginController.java
src/main/java/com/kakaotech/team14backend/outer/login/service/InstagramService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LogoutService.java
src/main/resources/application-local.yml

* 해당 api 호출 시 redis에 저장된 사용자 refreshToken 삭제
이슈번호 : #108

로그아웃 기능 추가

---

src/main/java/com/kakaotech/team14backend/auth/PrincipalDetails.java
src/main/java/com/kakaotech/team14backend/auth/PrincipalDetailsService.java
src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/outer/login/controller/LoginController.java

* CORS 설정 빈 주입 
* 테스트코드에서 withUserDetails 어노테이션을 사용하기위한 클래스 작성

CORS 설정 및 PrincipalDetailsService 클래스 작성

---

src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/outer/login/service/InstagramService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java

* CORS에 특정도메인을 추가하였고, SecurityFilterChain에서 직접 CorsConfigurationSource를 불러오게 수정하였습니다. 
* 크램풀린 배포를 위한 프록시설정으로 수정하였습니다

fix : CORS 설정 수정 및 프록시 설정 수정

---

src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/config/WebConfig.java
src/main/resources/application-local.yml

* 프론트엔드 배포 URL CORS 허용 추가 
* 카카오 callback주소 locahost:3000으로 지정

프론트엔드 배포 URL CORS 허용 추가 

---

src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/config/WebConfig.java
src/main/java/com/kakaotech/team14backend/filter/CorsFilter.java

fix : SecurityConfig 수정

---

src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/filter/CorsFilter.java

AllowedOrigins -> AllowedOriginPattern으로 변경
스프링부트 2.4.0 부터 전자 메소드로 "*"같은 패턴 불가하게 바뀌었다고 합니다

Cors 설정 추가 수정

---

src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
src/main/java/com/kakaotech/team14backend/jwt/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/team14backend/jwt/service/TokenService.java
src/test/java/com/kakaotech/team14backend/inner/post/usecase/SetPostLikeUsecaseTest.java

* 기존 컨트롤러를 보았을때 memberId가 필요해 토큰을 수정하였습니다.
* 수정사항으로 인한 테스트코드 변경

fix : 토큰에 memberId를 포함하도록 변경

---

src/main/java/com/kakaotech/team14backend/config/RestTemplateConfig.java
src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/outer/login/controller/LoginController.java
src/main/java/com/kakaotech/team14backend/outer/login/service/InstagramService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java

* SimpleClientHttpRequestFactory를 사용하는 방법으로 프록시설정을 변경하였습니다

fix : 프록시 설정 수정

---

src/main/java/com/kakaotech/team14backend/outer/post/schedule/SchedulePopularPost.java
src/main/resources/application-lab.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

인기 게시물을 Redis에 반영하는 initialDelay 스케줄링 값을 0ms 변경
관련 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/140

인기 게시물 스케줄링값 설정 이슈 해결

---

src/main/java/com/kakaotech/team14backend/outer/login/controller/LoginController.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java

로그인 중 에러 확인을 위해 임시로 코드를 추가하였습니다.

fix : 로그인 중 에러로그 확인

---

src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java
src/main/java/com/kakaotech/team14backend/outer/post/dto/UploadPostDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/dto/UploadPostRequestDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java
src/main/resources/application.yml

누락된 DTO 정보 추가 - 게시물 업로드시 해시태그, 닉네임, 이미지 이름 정보 누락
관련 이슈 : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/129

[Swagger] 누락된 DTO 정보 반영

---

src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java

실수로 로컬서버 사용하는 프록시미버전을 merge했습니다..!!

fix : LoginService 잘못된 코드 수정

---

src/main/java/com/kakaotech/team14backend/auth/PrincipalDetails.java
src/main/java/com/kakaotech/team14backend/config/RestTemplateConfig.java
src/main/java/com/kakaotech/team14backend/inner/member/repository/MemberRepository.java
src/main/java/com/kakaotech/team14backend/jwt/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/team14backend/outer/login/service/InstagramService.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java
src/main/java/com/kakaotech/team14backend/outer/member/controller/MemberController.java
src/main/java/com/kakaotech/team14backend/outer/member/service/MemberService.java

* 멘토님 피드백 반영하여 principalDetails 클래스와 RestTemplateConfig 클래스를 수정하였습니다.
* 회원탈퇴 기능을 개발하였습니다.

프록시서버 설정 변경 및 회원탈퇴 기능 개발

---

src/main/resources/application-prod.yml

토큰만료시간 너무 짧게 설정해서 연장하였습니다.
일단 현재 프론트에서 reissue api 테스트를 위해 5분으로 조정하였습니다!

fix : 토큰유효시간 정정

---

src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
src/main/resources/application-prod.yml

* redirectURL -> https://localhost:3000
* memberEntity의 kakaoId 유니크값으로 수정

redirectURL 변경 및 memberEntity 수정

---

src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostUsecase.java
src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java

인기 피드 게시글 좋아요 요청 후 좋아요가 반영 되지 않는 이슈 해결

---

src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java
src/main/java/com/kakaotech/team14backend/outer/member/dto/GetMemberInfoResponseDTO.java
src/main/java/com/kakaotech/team14backend/outer/member/service/MemberService.java
src/main/resources/application-local.yml

* 업로드권한 -> 인스타연동유저
* 마이페이지 조회에 인스타ID 정보 추가

업로드 권한 수정 및 마이페이지 조회 수정

---

src/main/java/com/kakaotech/team14backend/outer/post/dto/GetMyPostResponseDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPersonalPostResponseDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPopularPostDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPopularPostResponseDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPostResponseDTO.java
src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

관련 이슈  : https://github.com/Step3-kakao-tech-campus/Team14_BE/issues/147

응답시 외부 주소를 사용해 이미지 주소(URL) 응답하기

---

src/main/java/com/kakaotech/team14backend/outer/login/controller/LoginController.java
src/main/java/com/kakaotech/team14backend/outer/login/service/LoginService.java

createOrLoginMember 메소드 트랜잭션 처리

---

k8s/configs/init.sql
src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
src/main/java/com/kakaotech/team14backend/inner/post/port/PostUseCasePort.java
src/main/java/com/kakaotech/team14backend/inner/post/usecase/PostUsecaseImpl.java
src/main/java/com/kakaotech/team14backend/outer/member/dto/GetMemberInfoResponseDTO.java
src/main/java/com/kakaotech/team14backend/outer/member/service/MemberService.java
src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java
src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java
src/main/resources/db/prodMockSetup.sql
src/main/resources/db/testSetup.sql

feat: userInfo 업데이트로 유저의 받은 좋아요 수 반영
feat: user/info에 인스타그램 연동 여부와 포인트 추가
fix: total Like 초기화 의존성 제거
fix: 오타 수정
fix: Hash Tag Split 버그 해결
fix: 해시 태그 0번째 인덱스 잘리는 문제 수정
refactor: total Point 구조 개선
refactor: 게시글 생성 쿼리 최적화
refactor: instaId 필드 제거
refactor: /user/info 경로의 instId 필드 제거
refactor: 헥사고날(Hexagonal) 아키텍처로 마이그레이션을 위한 기반 작업
weekly 브랜치와의 병합 작업 여러 차례 진행

주요 기능 개선 및 코드 리팩토링

---

src/main/java/com/kakaotech/team14backend/outer/point/controller/PointController.java
src/main/java/com/kakaotech/team14backend/outer/point/dto/UsePointByPostRequestDTO.java
src/main/java/com/kakaotech/team14backend/outer/point/dto/UsePointByPostResponseDTO.java
src/main/java/com/kakaotech/team14backend/outer/point/usecase/usePointByPostUsecase.java

```shell
java.lang.IllegalArgumentException: No enum constant com.kakaotech.team14backend.inner.member.model.Status.STATUS_DORMANT
at java.base/java.lang.Enum.valueOf(Enum.java:273) ~[na:na]
at org.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.fromName(EnumJavaTypeDescriptor.java:84) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
at org.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.wrap(EnumJavaTypeDescriptor.java:54) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
at org.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.wrap(EnumJavaTypeDescriptor.java:16) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
at org.hibernate.type.descriptor.sql.VarcharTypeDescriptor$2.doExtract(VarcharTypeDescriptor.java:62) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
at …
```

Home feed에 인스타 Id 얻는 로직 추가

---

src/main/java/com/kakaotech/team14backend/inner/post/model/PostLevel.java

랭킹에 따른 반환 레벨 수정
